function plotAll(Pmvdr,Pmvdrsvm,Pmusic,Pmusicsvm,mindB)

figure;
subplot(221)
plot(linspace(-90,90,256),Pmvdr(:)-max(Pmvdr),'k');
ylabel("dB")
xlabel("Angle (degrees)")
ylim([mindB 0])
title("MVDR")
subplot(222)
plot(linspace(-90,90,256),Pmvdrsvm(:)-max(Pmvdrsvm),'k')
ylabel("dB")
xlabel("Angle (degrees)")
ylim([mindB 0])
title("SVM-MVDR")
subplot(223)
plot(linspace(-90,90,256),Pmusic(:)-max(Pmusic),'k')
ylabel("dB")
xlabel("Angle (degrees)")
ylim([mindB 0])
title("MUSIC")
subplot(224)
plot(linspace(-90,90,256),Pmusicsvm(:)-max(Pmusicsvm),'k')
ylabel("dB")
xlabel("Angle (degrees)")
ylim([mindB 0])
title("SVM-MUSIC")